sudo: required
language: python
python:
  - "3.8"

install:
  - sudo apt-get update
  - python3 -m pip install -r requirements.txt
  - python setup.py install

script: pytest tests

before_deploy:
  - cd docs && sphinx-apidoc -f -o ./source ../pfspinup -H Modules && make html && touch build/html/.nojekyll

deploy:
  provider: pages:git
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: build/html/
  edge: true
  on:
    branch: master, prep
